### ISSUE TITLE
Missing oc-utils.json file when github action run

### ISSUE THREAD

**Issue by supakornbabe** [redhat-developer/openshift-actions#12]
I follow the example provided on readme in your repository but when GitHub action runs this action it throw me these errors.

```
##[error]Error: ENOENT: no such file or directory, open '/Users/runner/runners/2.164.0/work/gh-action-test/gh-action-test/oc-utils.json'
##[error]Node run failed with exit code 1
```

I think the error happens because it can't find a URL link to download the client so I try to copy oc-utils.json to my repository then GitHub action can run all steps. I think you are missing the oc-utils.json file within your script. Please investigate and fix it. 

Thanks for your awesome actions.

**Comment by lstocchi** [comment]
Hi @supakornbabe sorry for the late response. I was sure i replied to you. My bad. Yeah, there was a problem with version 1.0. It was fixed in v1.1 . 
To make it work just change the version of the extension `uses: redhat-developer/openshift-actions@v1.1`

We removed 1.0 from marketplace but didn't update the documentation :/ Doing it now.
